-- Drop table

-- DROP TABLE SGIPD_DEV.dbo.docentes_cv_all_rows;

CREATE TABLE SGIPD_DEV.dbo.docentes_cv_all_rows (
	codigo_de_tramite bigint NULL,
	codigo_de_solicitante bigint NULL,
	codigo_de_tipo_de_tramite bigint NULL,
	nombres varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	apellidos varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	direccion_actual_de_residencia varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	departamento varchar(100) COLLATE Modern_Spanish_CI_AS NULL,
	municipio varchar(100) COLLATE Modern_Spanish_CI_AS NULL,
	nip varchar(18) COLLATE Modern_Spanish_CI_AS NULL,
	dui varchar(15) COLLATE Modern_Spanish_CI_AS NULL,
	correo varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	nivel_docente varchar(100) COLLATE Modern_Spanish_CI_AS NULL,
	telefono_fijo varchar(100) COLLATE Modern_Spanish_CI_AS NULL,
	telefono_celular varchar(100) COLLATE Modern_Spanish_CI_AS NULL,
	discapacidad varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	grado_academico_1 varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	especialidad_1 varchar(100) COLLATE Modern_Spanish_CI_AS NULL,
	institucion_educativa_1 varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	annio_de_graduacion_1 varchar(100) COLLATE Modern_Spanish_CI_AS NULL,
	grado_academico_2 varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	especialidad_2 varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	institucion_educativa_2 varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	annio_de_graduacion_2 varchar(100) COLLATE Modern_Spanish_CI_AS NULL,
	grado_academico_3 varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	especialidad_3 varchar(100) COLLATE Modern_Spanish_CI_AS NULL,
	institucion_educativa_3 varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	annio_de_graduacion_3 varchar(100) COLLATE Modern_Spanish_CI_AS NULL,
	grado_academico_4 varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	especialidad_4 varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	institucion_educativa_4 varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	annio_de_graduacion_4 varchar(100) COLLATE Modern_Spanish_CI_AS NULL,
	nombre_capacitacion_1 varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	cantidad_horas_1 bigint NULL,
	Institucion_1 varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	fecha_inicio_1 varchar(100) COLLATE Modern_Spanish_CI_AS NULL,
	fecha_finalizacion_1 varchar(100) COLLATE Modern_Spanish_CI_AS NULL,
	Pais_1 varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	diploma_obtenido_1 varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	nombre_capacitacion_2 varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	cantidad_horas_2 bigint NULL,
	Institucion_2 varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	fecha_inicio_2 varchar(100) COLLATE Modern_Spanish_CI_AS NULL,
	fecha_finalizacion_2 varchar(100) COLLATE Modern_Spanish_CI_AS NULL,
	Pais_2 varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	diploma_obtenido_2 varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	nombre_capacitacion_3 varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	cantidad_horas_3 bigint NULL,
	Institucion_3 varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	fecha_inicio_3 varchar(100) COLLATE Modern_Spanish_CI_AS NULL,
	fecha_finalizacion_3 varchar(100) COLLATE Modern_Spanish_CI_AS NULL,
	Pais_3 varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	diploma_obtenido_3 varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	nombre_capacitacion_4 varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	cantidad_horas_4 bigint NULL,
	Institucion_4 varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	fecha_inicio_4 varchar(100) COLLATE Modern_Spanish_CI_AS NULL,
	fecha_finalizacion_4 varchar(100) COLLATE Modern_Spanish_CI_AS NULL,
	Pais_4 varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	diploma_obtenido_4 varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	nombre_capacitacion_5 varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	cantidad_horas_5 bigint NULL,
	Institucion_5 varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	fecha_inicio_5 varchar(100) COLLATE Modern_Spanish_CI_AS NULL,
	fecha_finalizacion_5 varchar(100) COLLATE Modern_Spanish_CI_AS NULL,
	Pais_5 varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	diploma_obtenido_5 varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	institucion_educativa_nacional_1 varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	institucion_educativa_extranjero_1 varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	cantidad_de_annios_1 bigint NULL,
	departamento_1 varchar(100) COLLATE Modern_Spanish_CI_AS NULL,
	municipio_1 varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	desde_1 varchar(100) COLLATE Modern_Spanish_CI_AS NULL,
	hasta_1 varchar(100) COLLATE Modern_Spanish_CI_AS NULL,
	nombramiento_1 varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	sector_1 varchar(100) COLLATE Modern_Spanish_CI_AS NULL,
	institucion_educativa_nacional_2 varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	institucion_educativa_extranjero_2 varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	cantidad_de_annios_2 bigint NULL,
	departamento_2 varchar(100) COLLATE Modern_Spanish_CI_AS NULL,
	municipio_2 varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	desde_2 varchar(100) COLLATE Modern_Spanish_CI_AS NULL,
	hasta_2 varchar(100) COLLATE Modern_Spanish_CI_AS NULL,
	nombramiento_2 varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	sector_2 varchar(100) COLLATE Modern_Spanish_CI_AS NULL,
	institucion_educativa_nacional_3 varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	institucion_educativa_extranjero_3 varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	cantidad_de_annios_3 bigint NULL,
	departamento_3 varchar(100) COLLATE Modern_Spanish_CI_AS NULL,
	municipio_3 varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	desde_3 varchar(100) COLLATE Modern_Spanish_CI_AS NULL,
	hasta_3 varchar(100) COLLATE Modern_Spanish_CI_AS NULL,
	nombramiento_3 varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	sector_3 varchar(100) COLLATE Modern_Spanish_CI_AS NULL,
	institucion_educativa_nacional_4 varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	institucion_educativa_extranjero_4 varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	cantidad_de_annios_4 bigint NULL,
	departamento_4 varchar(100) COLLATE Modern_Spanish_CI_AS NULL,
	municipio_4 varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	desde_4 varchar(100) COLLATE Modern_Spanish_CI_AS NULL,
	hasta_4 varchar(100) COLLATE Modern_Spanish_CI_AS NULL,
	nombramiento_4 varchar(255) COLLATE Modern_Spanish_CI_AS NULL,
	sector_4 varchar(100) COLLATE Modern_Spanish_CI_AS NULL
);
